# Generated by Django 4.1.6 on 2023-11-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/')),
                ('bg_image', models.ImageField(upload_to='banners/')),
                ('text1', models.CharField(max_length=250)),
                ('text2', models.CharField(max_length=250)),
                ('image2', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
