# Generated by Django 4.1.6 on 2023-11-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_diseaseimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('diseases', models.ManyToManyField(to='main.disease')),
            ],
        ),
        migrations.DeleteModel(
            name='DiseaseImage',
        ),
    ]
