# Generated by Django 4.1.6 on 2023-11-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_howtouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.CharField(max_length=250)),
            ],
        ),
    ]
