# Generated by Django 4.1.6 on 2023-11-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_numberfact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberfact',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
