# Generated by Django 4.1.6 on 2023-11-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_numberfact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('info', models.CharField(max_length=250)),
                ('tg', models.URLField()),
                ('fb', models.URLField()),
                ('inst', models.URLField()),
                ('yt', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='mainbanner',
            name='logo',
        ),
    ]
